"""
Script untuk menambahkan komentar penjelasan detail ke setiap code cell
di notebook UAS_BENGKOD.ipynb agar lebih mudah dipahami saat presentasi.
"""

import json
import copy

with open('notebook/UAS_BENGKOD.ipynb', encoding='utf-8') as f:
    nb = json.load(f)

# Backup dulu
with open('notebook/UAS_BENGKOD_BACKUP.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

# ───────────────────────────────────────────────────────────────────
#  DEFINISI KOMENTAR UNTUK SETIAP CODE CELL
#  Format: cell_index -> list of source lines (string)
#  Kita REPLACE seluruh source cell dengan versi yang sudah di-comment
# ───────────────────────────────────────────────────────────────────

comments = {}

# ═══════════════════════════════════════════════════════════════
# CELL 4 — Import Library
# ═══════════════════════════════════════════════════════════════
comments[4] = [
    "# ============================================================\n",
    "# IMPORT LIBRARY\n",
    "# ============================================================\n",
    "# pandas   → Manipulasi dan analisis data tabular (DataFrame)\n",
    "# numpy    → Komputasi numerik (array, statistik)\n",
    "# matplotlib → Visualisasi dasar (chart, plot)\n",
    "# seaborn  → Visualisasi statistik tingkat lanjut (heatmap, KDE)\n",
    "# warnings → Menyembunyikan warning yang tidak relevan\n",
    "# ============================================================\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')  # Sembunyikan warning agar output lebih bersih\n",
    "\n",
    "# Konfigurasi tampilan:\n",
    "pd.set_option('display.max_columns', None)  # Tampilkan semua kolom di DataFrame\n",
    "sns.set_theme(style=\"whitegrid\")             # Tema seaborn: background grid putih\n",
    "plt.rcParams['figure.figsize'] = (10, 5)     # Ukuran default semua plot: 10x5 inch\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 6 — Komentar Google Colab (tidak dipakai)
# ═══════════════════════════════════════════════════════════════
comments[6] = [
    "# ============================================================\n",
    "# CATATAN: Notebook ini dijalankan di VSCode (lokal),\n",
    "# sehingga TIDAK perlu mount Google Drive.\n",
    "# Baris di bawah ini hanya relevan jika pakai Google Colab.\n",
    "# ============================================================\n",
    "\n",
    "# from google.colab import drive\n",
    "# drive.mount('/content/drive')\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 7 — Setup Environment
# ═══════════════════════════════════════════════════════════════
comments[7] = [
    "# ============================================================\n",
    "# SETUP ENVIRONMENT — Konfigurasi Path Direktori\n",
    "# ============================================================\n",
    "# Menentukan path direktori utama project secara dinamis.\n",
    "# Struktur folder:\n",
    "#   BASE_DIR/\n",
    "#     ├── data/       → Folder untuk data hasil olahan\n",
    "#     ├── dataset/    → Dataset mentah (CSV)\n",
    "#     ├── model/      → Model ML yang sudah dilatih (.pkl)\n",
    "#     ├── app/        → Aplikasi Streamlit (app.py)\n",
    "#     └── notebook/   → Notebook ini\n",
    "# ============================================================\n",
    "\n",
    "import os\n",
    "\n",
    "# Naik 1 level dari folder notebook/ ke ROOT project\n",
    "BASE_DIR    = os.path.dirname(os.path.dirname(os.path.abspath('__file__')))\n",
    "DATASET_DIR = os.path.join(BASE_DIR, 'data')\n",
    "MODEL_DIR   = os.path.join(BASE_DIR, 'model')\n",
    "APP_DIR     = os.path.join(BASE_DIR, 'app')\n",
    "\n",
    "# Buat folder secara otomatis jika belum ada\n",
    "os.makedirs(DATASET_DIR, exist_ok=True)\n",
    "os.makedirs(MODEL_DIR,   exist_ok=True)\n",
    "os.makedirs(APP_DIR,     exist_ok=True)\n",
    "\n",
    "print('✅ Setup environment VSCode selesai!')\n",
    "print(f'   BASE_DIR    : {BASE_DIR}')\n",
    "print(f'   DATASET_DIR : {DATASET_DIR}')\n",
    "print(f'   MODEL_DIR   : {MODEL_DIR}')\n",
    "print(f'   APP_DIR     : {APP_DIR}')\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 8 — Path Dinamis (Fallback)
# ═══════════════════════════════════════════════════════════════
comments[8] = [
    "# ============================================================\n",
    "# PATH DINAMIS — Mencari lokasi folder dataset\n",
    "# ============================================================\n",
    "# Karena Jupyter Notebook tidak punya __file__ bawaan,\n",
    "# kita perlu mendeteksi path secara manual.\n",
    "# Fallback: gunakan path absolut langsung jika deteksi gagal.\n",
    "# ============================================================\n",
    "\n",
    "import os\n",
    "\n",
    "# Coba deteksi path otomatis berdasarkan lokasi notebook\n",
    "base_dir = os.path.dirname(os.path.abspath('__file__' if '__file__' in dir() else os.getcwd()))\n",
    "dataset_dir = os.path.join(os.path.dirname(os.getcwd()), 'dataset') if os.path.basename(os.getcwd()) == 'notebook' else os.path.join(os.getcwd(), 'dataset')\n",
    "\n",
    "# Fallback: path absolut langsung ke folder dataset\n",
    "DATASET_PATH = r'c:\\Users\\Lenovo\\OneDrive\\Pictures\\Documents\\KULIAH\\BENGKOD\\UAS-Bengkel-Koding-DataScience\\dataset'\n",
    "print(os.listdir(DATASET_PATH))  # Verifikasi file yang ada di folder dataset\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 9 — Load Dataset
# ═══════════════════════════════════════════════════════════════
comments[9] = [
    "# ============================================================\n",
    "# LOAD DATASET — Membaca CSV ke dalam DataFrame\n",
    "# ============================================================\n",
    "# Dataset: \"Sales - Marketing customer dataset.csv\"\n",
    "# Sumber : Kaggle (https://www.kaggle.com/datasets/bhaskerpaul/sales-and-marketing-dataset)\n",
    "# Isi    : 15.000 data pelanggan dengan 30 kolom fitur\n",
    "# Target : Kolom 'churn' (0=Tidak Churn, 1=Churn)\n",
    "# ============================================================\n",
    "\n",
    "import os\n",
    "\n",
    "# Path absolut langsung ke file dataset\n",
    "DATASET_PATH = r'c:\\Users\\Lenovo\\OneDrive\\Pictures\\Documents\\KULIAH\\BENGKOD\\UAS-Bengkel-Koding-DataScience\\dataset\\Sales - Marketing customer dataset.csv'\n",
    "\n",
    "# Baca CSV menjadi DataFrame pandas\n",
    "df = pd.read_csv(DATASET_PATH)\n",
    "\n",
    "# Tampilkan info singkat tentang dataset yang berhasil dimuat\n",
    "print(\"Dataset berhasil dimuat!\")\n",
    "print(f\"   Jumlah baris : {df.shape[0]:,}\")  # 15.000 baris\n",
    "print(f\"   Jumlah kolom : {df.shape[1]}\")     # 30 kolom\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 10 — Tampilkan 5 baris pertama
# ═══════════════════════════════════════════════════════════════
comments[10] = [
    "# Tampilkan 5 baris pertama dataset untuk melihat struktur data\n",
    "# Berguna untuk memahami format kolom, tipe data awal, dan sampel nilai\n",
    "print(\"\\n📌 5 Baris Pertama:\")\n",
    "display(df.head())\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 11 — Info Dataset
# ═══════════════════════════════════════════════════════════════
comments[11] = [
    "# Tampilkan informasi detail dataset:\n",
    "# - Jumlah baris dan kolom\n",
    "# - Nama kolom beserta tipe datanya (int64, float64, object)\n",
    "# - Jumlah non-null values per kolom (untuk deteksi missing value)\n",
    "# - Penggunaan memori\n",
    "print(\"\\n📌 Informasi Dataset:\")\n",
    "df.info()\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 13 — Statistik Deskriptif
# ═══════════════════════════════════════════════════════════════
comments[13] = [
    "# ============================================================\n",
    "# STATISTIK DESKRIPTIF\n",
    "# ============================================================\n",
    "# describe(include='all') menampilkan ringkasan statistik:\n",
    "# - Numerik : count, mean, std, min, 25%, 50%, 75%, max\n",
    "# - Kategorikal : count, unique, top (modus), freq\n",
    "# .T (transpose) → kolom jadi baris agar lebih mudah dibaca\n",
    "# ============================================================\n",
    "\n",
    "print(\"\\n📌 Statistik Deskriptif:\")\n",
    "display(df.describe(include='all').T)\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 15 — Missing Value (tabel)
# ═══════════════════════════════════════════════════════════════
comments[15] = [
    "# ============================================================\n",
    "# CEK MISSING VALUE\n",
    "# ============================================================\n",
    "# Menghitung jumlah dan persentase missing value per kolom.\n",
    "# Missing value perlu ditangani karena:\n",
    "# 1. Bisa menyebabkan error saat training model\n",
    "# 2. Mengurangi kualitas dan akurasi prediksi\n",
    "# ============================================================\n",
    "\n",
    "missing = df.isnull().sum()                    # Jumlah NaN per kolom\n",
    "missing_pct = (missing / len(df)) * 100        # Konversi ke persentase\n",
    "\n",
    "# Buat tabel ringkasan missing value\n",
    "missing_df = pd.DataFrame({\n",
    "    'Jumlah Missing': missing,\n",
    "    'Persentase (%)': round(missing_pct, 2)\n",
    "}).sort_values('Persentase (%)', ascending=False)\n",
    "\n",
    "# Tampilkan hanya kolom yang memiliki missing value (> 0)\n",
    "display(missing_df[missing_df['Jumlah Missing'] > 0])\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 16 — Missing Value (visualisasi)
# ═══════════════════════════════════════════════════════════════
comments[16] = [
    "# ============================================================\n",
    "# VISUALISASI MISSING VALUE\n",
    "# ============================================================\n",
    "# Jika ada kolom dengan missing value, tampilkan bar chart\n",
    "# persentasenya agar mudah dilihat kolom mana yang paling\n",
    "# banyak missing.\n",
    "# ============================================================\n",
    "\n",
    "# Filter kolom yang punya missing value\n",
    "cols_missing = missing_pct[missing_pct > 0]\n",
    "\n",
    "if len(cols_missing) > 0:\n",
    "    plt.figure(figsize=(12, 5))\n",
    "    cols_missing.sort_values(ascending=False).plot(\n",
    "        kind='bar', color='steelblue', edgecolor='black'\n",
    "    )\n",
    "    plt.title('Persentase Missing Value per Kolom', fontsize=14, fontweight='bold')\n",
    "    plt.xlabel('Kolom')\n",
    "    plt.ylabel('Persentase (%)')\n",
    "    plt.xticks(rotation=45, ha='right')\n",
    "    # Tambahkan label angka di atas setiap bar\n",
    "    for i, v in enumerate(cols_missing.sort_values(ascending=False)):\n",
    "        plt.text(i, v + 0.05, f'{v:.2f}%', ha='center', fontsize=9)\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "else:\n",
    "    print(\"\\n✅ Tidak ada missing value dalam dataset!\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 17 — Cek Duplikasi
# ═══════════════════════════════════════════════════════════════
comments[17] = [
    "# Cek apakah ada baris duplikat di dataset\n",
    "# Baris duplikat bisa menyebabkan bias (data yang sama dihitung 2x)\n",
    "print(f\"\\n=== CEK DUPLIKASI ===\")\n",
    "print(f\"Jumlah baris duplikat : {df.duplicated().sum()}\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 19 — Distribusi Target Churn
# ═══════════════════════════════════════════════════════════════
comments[19] = [
    "# ============================================================\n",
    "# VISUALISASI DISTRIBUSI TARGET — Churn\n",
    "# ============================================================\n",
    "# TUJUAN: Melihat proporsi kelas target (churn vs tidak churn).\n",
    "# Ini PENTING karena menentukan strategi evaluasi model.\n",
    "#\n",
    "# HASIL: Data IMBALANCED → ~85% tidak churn, ~15% churn\n",
    "# DAMPAK: Model akan bias memprediksi \"tidak churn\" → perlu\n",
    "#         fokus pada F1-Score & Recall, bukan Accuracy saja.\n",
    "# ============================================================\n",
    "\n",
    "# Hitung jumlah dan persentase masing-masing kelas\n",
    "churn_counts = df['churn'].value_counts()               # Jumlah absolut\n",
    "churn_pct    = df['churn'].value_counts(normalize=True) * 100  # Persentase\n",
    "\n",
    "# Tampilkan tabel distribusi\n",
    "print(\"=== DISTRIBUSI TARGET CHURN ===\")\n",
    "print(pd.DataFrame({\n",
    "    'Jumlah'        : churn_counts,\n",
    "    'Persentase (%)': churn_pct.round(2)\n",
    "}))\n",
    "\n",
    "# ── Visualisasi: Bar Chart + Pie Chart ──\n",
    "fig, axes = plt.subplots(1, 2, figsize=(10, 5))\n",
    "\n",
    "# Bar chart → menunjukkan perbedaan jumlah absolut\n",
    "axes[0].bar(['Tidak Churn (0)', 'Churn (1)'],\n",
    "            churn_counts.values,\n",
    "            color=['#2196F3', '#F44336'])  # Biru=aman, Merah=churn\n",
    "for i, (val, pct) in enumerate(zip(churn_counts.values, churn_pct.values)):\n",
    "    axes[0].text(i, val + 100, f'{val:,}\\n({pct:.1f}%)',\n",
    "                 ha='center', fontsize=11, fontweight='bold')\n",
    "axes[0].set_title('Distribusi Churn', fontsize=13, fontweight='bold')\n",
    "axes[0].set_ylabel('Jumlah Pelanggan')\n",
    "axes[0].set_ylim(0, max(churn_counts.values) * 1.15)\n",
    "\n",
    "# Pie chart → menunjukkan proporsi/rasio\n",
    "axes[1].pie(churn_counts.values,\n",
    "            labels=['Tidak Churn (0)', 'Churn (1)'],\n",
    "            autopct='%1.1f%%',\n",
    "            colors=['#2196F3', '#F44336'],\n",
    "            startangle=90)\n",
    "axes[1].set_title('Proporsi Churn', fontsize=13, fontweight='bold')\n",
    "\n",
    "plt.suptitle('Distribusi Variabel Target - Churn', fontsize=14, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Catatan penting tentang data imbalanced\n",
    "print(\"\\n⚠️  Catatan: Data IMBALANCED — rasio Tidak Churn:Churn ≈ 5.5:1\")\n",
    "print(\"     Fokus evaluasi pada F1-Score dan Recall kelas Churn (1)\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 21 — Analisis Outlier (Boxplot)
# ═══════════════════════════════════════════════════════════════
comments[21] = [
    "# ============================================================\n",
    "# ANALISIS OUTLIER — Boxplot 9 Fitur Numerik\n",
    "# ============================================================\n",
    "# TUJUAN: Mendeteksi outlier (nilai ekstrem) di fitur numerik.\n",
    "# METODE: Boxplot → menampilkan Q1, Q3, IQR, dan titik outlier.\n",
    "#\n",
    "# Outlier bisa memengaruhi performa model, terutama:\n",
    "# - Logistic Regression (sensitif terhadap skala)\n",
    "# - KNN (sensitif terhadap jarak Euclidean)\n",
    "#\n",
    "# TEMUAN: Ditemukan anomali pada kolom 'age':\n",
    "#   - 3 data dengan usia negatif (tidak valid)\n",
    "#   - 30 data dengan usia > 80\n",
    "# ============================================================\n",
    "\n",
    "# Pilih 9 fitur numerik utama untuk analisis\n",
    "num_cols = ['age', 'total_spent', 'avg_order_value', 'lifetime_value',\n",
    "            'avg_session_time', 'pages_per_session', 'total_visits',\n",
    "            'satisfaction_score', 'marketing_spend_per_user']\n",
    "\n",
    "# Buat grid 3x3 boxplot\n",
    "fig, axes = plt.subplots(3, 3, figsize=(14, 10))\n",
    "axes = axes.flatten()  # Ubah 2D array axes menjadi 1D agar mudah di-loop\n",
    "\n",
    "for i, col in enumerate(num_cols):\n",
    "    axes[i].boxplot(df[col].dropna(), vert=True, patch_artist=True,\n",
    "                    boxprops=dict(facecolor='#90CAF9'))\n",
    "    axes[i].set_title(col, fontsize=10, fontweight='bold')\n",
    "    axes[i].set_ylabel('Nilai')\n",
    "\n",
    "plt.suptitle('Analisis Outlier - Boxplot Fitur Numerik',\n",
    "             fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Cek anomali spesifik pada kolom 'age'\n",
    "print(\"=== CEK ANOMALI age ===\")\n",
    "print(f\"Jumlah age negatif  : {(df['age'] < 0).sum()}\")   # Usia < 0 (tidak valid!)\n",
    "print(f\"Jumlah age > 80     : {(df['age'] > 80).sum()}\")   # Usia sangat tua\n",
    "print(f\"Min age             : {df['age'].min()}\")           # Nilai usia minimum\n",
    "print(f\"Max age             : {df['age'].max()}\")           # Nilai usia maksimum\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 23 — Heatmap Korelasi
# ═══════════════════════════════════════════════════════════════
comments[23] = [
    "# ============================================================\n",
    "# HEATMAP KORELASI FITUR NUMERIK\n",
    "# ============================================================\n",
    "# TUJUAN: Melihat hubungan linear antar fitur numerik.\n",
    "# METODE: Korelasi Pearson → nilai -1 s/d +1\n",
    "#   +1 = korelasi positif sempurna (naik bersama)\n",
    "#    0 = tidak ada korelasi linear\n",
    "#   -1 = korelasi negatif sempurna (berbanding terbalik)\n",
    "#\n",
    "# INSIGHT PENTING:\n",
    "# - Jika ada 2 fitur berkorelasi tinggi (>0.8), salah satu\n",
    "#   bisa di-drop untuk menghindari multikolinearitas\n",
    "# - Korelasi terhadap 'churn' menunjukkan fitur mana yang\n",
    "#   paling berpengaruh untuk prediksi\n",
    "# ============================================================\n",
    "\n",
    "# Pilih semua kolom numerik, kecuali customer_id (hanya identifier)\n",
    "num_cols_corr = df.select_dtypes(include=[np.number]).columns.tolist()\n",
    "num_cols_corr.remove('customer_id')\n",
    "\n",
    "# Hitung matriks korelasi Pearson\n",
    "corr_matrix = df[num_cols_corr].corr()\n",
    "\n",
    "# Plot heatmap korelasi\n",
    "plt.figure(figsize=(14, 10))\n",
    "sns.heatmap(corr_matrix,\n",
    "            annot=True, fmt='.2f',      # Tampilkan angka korelasi 2 desimal\n",
    "            cmap='coolwarm', center=0,   # Warna: biru=negatif, merah=positif\n",
    "            linewidths=0.5,\n",
    "            annot_kws={'size': 8})\n",
    "plt.title('Heatmap Korelasi Fitur Numerik', fontsize=14, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Tampilkan 10 fitur dengan korelasi tertinggi terhadap target 'churn'\n",
    "print(\"=== TOP KORELASI TERHADAP CHURN ===\")\n",
    "churn_corr = corr_matrix['churn'].drop('churn').abs().sort_values(ascending=False)\n",
    "display(churn_corr.head(10).to_frame('Korelasi Absolut'))\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 27 — Persiapan Fitur & Target (Direct Modeling)
# ═══════════════════════════════════════════════════════════════
comments[27] = [
    "# ============================================================\n",
    "# PERSIAPAN FITUR & TARGET — Direct Modeling (Tanpa Preprocessing)\n",
    "# ============================================================\n",
    "# Pada skenario Direct Modeling:\n",
    "# - Kolom kategorikal (object) HARUS di-drop karena model ML\n",
    "#   hanya bisa menerima input numerik\n",
    "# - Kolom datetime juga di-drop (belum ada feature engineering)\n",
    "# - customer_id di-drop (hanya identifier, bukan fitur prediktif)\n",
    "#\n",
    "# CATATAN: Ini adalah skenario BASELINE — performa paling dasar\n",
    "# tanpa optimasi apapun. Hasilnya akan dibandingkan dengan\n",
    "# skenario Preprocessing (Bagian 3) dan Tuning (Bagian 4).\n",
    "# ============================================================\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"     PERSIAPAN FITUR & TARGET (X dan y)\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "# Drop kolom non-numerik (tidak bisa langsung dipakai model)\n",
    "cols_to_drop = ['gender', 'country', 'city', 'acquisition_channel',\n",
    "                'device_type', 'subscription_type', 'coupon_code',\n",
    "                'payment_method', 'signup_date', 'last_purchase_date',\n",
    "                'customer_id']\n",
    "\n",
    "df_direct = df.drop(columns=cols_to_drop)\n",
    "\n",
    "# Cek missing value sebelum dropna\n",
    "print(f\"\\n  Missing value sebelum dropna:\")\n",
    "print(df_direct.isnull().sum()[df_direct.isnull().sum() > 0].to_string())\n",
    "\n",
    "# Drop semua baris yang masih ada NaN (cara paling sederhana)\n",
    "df_direct = df_direct.dropna()\n",
    "\n",
    "# Verifikasi tidak ada NaN tersisa\n",
    "print(f\"\\n  Missing value setelah dropna : {df_direct.isnull().sum().sum()}\")\n",
    "print(f\"  Shape setelah dropna         : {df_direct.shape}\")\n",
    "\n",
    "# Pisahkan fitur (X) dan target (y)\n",
    "X = df_direct.drop(columns=['churn'])  # X = semua kolom kecuali churn\n",
    "y = df_direct['churn']                  # y = kolom target (0/1)\n",
    "\n",
    "# Verifikasi final\n",
    "print(f\"\\n  ✅ Cek NaN di X : {pd.DataFrame(X).isnull().sum().sum()}\")\n",
    "print(f\"  Fitur prediktor (X) : {X.shape[1]} kolom\")\n",
    "print(f\"  Variabel target (y) : {y.shape[0]:,} baris\")\n",
    "print(f\"\\n  Kolom X yang digunakan:\")\n",
    "print(list(X.columns))\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 29 — Train Test Split (Direct)
# ═══════════════════════════════════════════════════════════════
comments[29] = [
    "# ============================================================\n",
    "# TRAIN TEST SPLIT — Membagi data menjadi data latih & uji\n",
    "# ============================================================\n",
    "# Pembagian: 80% training, 20% testing\n",
    "#\n",
    "# Parameter penting:\n",
    "# - test_size=0.2    → 20% data untuk testing\n",
    "# - random_state=42  → seed agar hasil bisa direproduksi\n",
    "# - stratify=y       → menjaga PROPORSI churn tetap sama\n",
    "#                      di train & test (sangat penting untuk\n",
    "#                      data imbalanced!)\n",
    "# ============================================================\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "X_train_d, X_test_d, y_train_d, y_test_d = train_test_split(\n",
    "    X, y,                # Fitur (X) dan target (y)\n",
    "    test_size=0.2,       # 20% data untuk testing\n",
    "    random_state=42,     # Seed untuk reprodusibilitas\n",
    "    stratify=y           # Jaga proporsi kelas churn di kedua set\n",
    ")\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"           TRAIN TEST SPLIT\")\n",
    "print(\"=\" * 60)\n",
    "print(f\"\\n  Total data    : {len(X):,}\")\n",
    "print(f\"  Data latih    : {len(X_train_d):,} (80%)\")\n",
    "print(f\"  Data uji      : {len(X_test_d):,}  (20%)\")\n",
    "print(f\"\\n  Distribusi y_train:\")\n",
    "print(y_train_d.value_counts().to_string())\n",
    "print(f\"\\n  Distribusi y_test:\")\n",
    "print(y_test_d.value_counts().to_string())\n",
    "print(f\"\\n  ✅ NaN di X_train_d : {pd.DataFrame(X_train_d).isnull().sum().sum()}\")\n",
    "print(f\"  ✅ NaN di X_test_d  : {pd.DataFrame(X_test_d).isnull().sum().sum()}\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 31 — Debug Step by Step
# ═══════════════════════════════════════════════════════════════
comments[31] = [
    "# ============================================================\n",
    "# DEBUG — Validasi Data Sebelum Training\n",
    "# ============================================================\n",
    "# Langkah penting sebelum melatih model:\n",
    "# 1. Cek NaN → model scikit-learn error jika ada NaN\n",
    "# 2. Cek Infinity → inf juga menyebabkan error\n",
    "# 3. Cek Dtype → pastikan semua kolom numerik\n",
    "# ============================================================\n",
    "\n",
    "import numpy as np\n",
    "\n",
    "# Cek 1: Apakah ada NaN di data training?\n",
    "print(\"=\" * 50)\n",
    "print(\"CEK 1 — NaN di X\")\n",
    "print(\"=\" * 50)\n",
    "x_df = pd.DataFrame(X_train_d)\n",
    "nan_cols = x_df.isnull().sum()\n",
    "print(nan_cols[nan_cols > 0])           # Hanya tampilkan kolom yang punya NaN\n",
    "print(f\"Total NaN: {x_df.isnull().sum().sum()}\")\n",
    "\n",
    "# Cek 2: Apakah ada nilai infinity?\n",
    "print(\"\\n\" + \"=\" * 50)\n",
    "print(\"CEK 2 — Infinity values\")\n",
    "print(\"=\" * 50)\n",
    "inf_check = np.isinf(x_df.select_dtypes(include=np.number)).sum()\n",
    "print(inf_check[inf_check > 0])\n",
    "\n",
    "# Cek 3: Tipe data setiap kolom (harus numerik semua)\n",
    "print(\"\\n\" + \"=\" * 50)\n",
    "print(\"CEK 3 — Dtype semua kolom\")\n",
    "print(\"=\" * 50)\n",
    "print(x_df.dtypes)\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 32 — Definisi 3 Model
# ═══════════════════════════════════════════════════════════════
comments[32] = [
    "# ============================================================\n",
    "# DEFINISI 3 MODEL MACHINE LEARNING\n",
    "# ============================================================\n",
    "# 1. LOGISTIC REGRESSION (Konvensional)\n",
    "#    → Model linear klasik untuk klasifikasi biner\n",
    "#    → Kelebihan: cepat, mudah diinterpretasi\n",
    "#    → Kekurangan: asumsi hubungan linear fitur-target\n",
    "#\n",
    "# 2. RANDOM FOREST (Ensemble Bagging)\n",
    "#    → Menggabungkan banyak Decision Tree (voting mayoritas)\n",
    "#    → Kelebihan: robust, tidak mudah overfitting, bisa\n",
    "#      menangkap pola non-linear\n",
    "#    → Kekurangan: lebih lambat, kurang interpretable\n",
    "#\n",
    "# 3. VOTING CLASSIFIER (Ensemble Voting)\n",
    "#    → Menggabungkan 3 model berbeda (LR + SVM + KNN)\n",
    "#    → voting='soft' → rata-rata probabilitas (bukan voting hard)\n",
    "#    → Kelebihan: generalisasi lebih baik\n",
    "#    → Kekurangan: waktu training paling lama\n",
    "# ============================================================\n",
    "\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.ensemble import RandomForestClassifier, VotingClassifier\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "\n",
    "# 1. Model Konvensional → Logistic Regression\n",
    "model_lr = LogisticRegression(random_state=42, max_iter=1000)\n",
    "\n",
    "# 2. Model Ensemble Bagging → Random Forest\n",
    "model_rf = RandomForestClassifier(random_state=42)\n",
    "\n",
    "# 3. Model Ensemble Voting → Gabungan LR + SVM + KNN\n",
    "estimators = [\n",
    "    ('lr',  LogisticRegression(random_state=42, max_iter=1000)),\n",
    "    ('svm', SVC(probability=True, random_state=42)),  # probability=True untuk soft voting\n",
    "    ('knn', KNeighborsClassifier())                    # KNN default k=5\n",
    "]\n",
    "model_voting = VotingClassifier(estimators=estimators, voting='soft')\n",
    "\n",
    "# Simpan ke dictionary agar mudah di-loop saat training\n",
    "models = {\n",
    "    'Logistic Regression (Konvensional)' : model_lr,\n",
    "    'Random Forest (Ensemble Bagging)'   : model_rf,\n",
    "    'Voting Classifier (LR + SVM + KNN)' : model_voting\n",
    "}\n",
    "\n",
    "print(\"\\n✅ Model yang akan dilatih:\")\n",
    "for i, name in enumerate(models.keys(), 1):\n",
    "    print(f\"   {i}. {name}\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 34 — Training & Evaluasi
# ═══════════════════════════════════════════════════════════════
comments[34] = [
    "# ============================================================\n",
    "# TRAINING & EVALUASI — Direct Modeling\n",
    "# ============================================================\n",
    "# Proses: Loop semua model → fit(train) → predict(test) → evaluasi\n",
    "#\n",
    "# Metrik evaluasi yang digunakan:\n",
    "# - Accuracy  : % prediksi benar secara keseluruhan\n",
    "# - Precision : Dari yang diprediksi churn, berapa % yang benar?\n",
    "# - Recall    : Dari yang BENAR churn, berapa % yang terdeteksi?\n",
    "# - F1-Score  : Harmonik mean Precision & Recall (metrik utama!)\n",
    "#\n",
    "# MENGAPA F1-Score jadi metrik utama?\n",
    "# → Karena data imbalanced (85:15), Accuracy bisa menyesatkan.\n",
    "#   Model yang selalu prediksi \"tidak churn\" sudah 85% akurat!\n",
    "# ============================================================\n",
    "\n",
    "from sklearn.metrics import (accuracy_score, precision_score,\n",
    "                              recall_score, f1_score,\n",
    "                              confusion_matrix, classification_report)\n",
    "import time\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"       TRAINING & EVALUASI MODEL\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "results = {}  # Dictionary untuk menyimpan hasil semua model\n",
    "\n",
    "for name, model in models.items():\n",
    "    print(f\"\\n⏳ Melatih: {name}...\")\n",
    "\n",
    "    start    = time.time()\n",
    "    model.fit(X_train_d, y_train_d)   # Training: model belajar dari data latih\n",
    "    duration = time.time() - start\n",
    "\n",
    "    y_pred = model.predict(X_test_d)  # Prediksi: model memprediksi data uji\n",
    "\n",
    "    # Hitung 4 metrik evaluasi\n",
    "    acc  = accuracy_score(y_test_d, y_pred)   # Akurasi keseluruhan\n",
    "    prec = precision_score(y_test_d, y_pred)  # Precision kelas churn (1)\n",
    "    rec  = recall_score(y_test_d, y_pred)     # Recall kelas churn (1)\n",
    "    f1   = f1_score(y_test_d, y_pred)         # F1 = 2 * (prec*rec)/(prec+rec)\n",
    "\n",
    "    results[name] = {\n",
    "        'Accuracy' : acc,\n",
    "        'Precision': prec,\n",
    "        'Recall'   : rec,\n",
    "        'F1-Score' : f1,\n",
    "        'Waktu (s)': round(duration, 2)\n",
    "    }\n",
    "\n",
    "    print(f\"   ✅ Selesai dalam {duration:.2f} detik\")\n",
    "    print(f\"   Accuracy : {acc:.4f} | Precision: {prec:.4f} | Recall: {rec:.4f} | F1: {f1:.4f}\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 36 — Tabel Perbandingan
# ═══════════════════════════════════════════════════════════════
comments[36] = [
    "# ============================================================\n",
    "# TABEL PERBANDINGAN & VISUALISASI BAR CHART — Direct Modeling\n",
    "# ============================================================\n",
    "# Menampilkan tabel performa 3 model dalam format yang rapi,\n",
    "# diurutkan berdasarkan F1-Score (tertinggi di atas).\n",
    "# ============================================================\n",
    "\n",
    "# Konversi results dictionary ke DataFrame, urutkan berdasarkan F1-Score\n",
    "results_df = pd.DataFrame(results).T\n",
    "results_df = results_df.sort_values('F1-Score', ascending=False)\n",
    "\n",
    "# Tampilkan tabel dengan gradient warna (semakin hijau = semakin baik)\n",
    "display(results_df.style\n",
    "        .format({'Accuracy':'{:.4f}', 'Precision':'{:.4f}',\n",
    "                 'Recall':'{:.4f}', 'F1-Score':'{:.4f}'})\n",
    "        .background_gradient(subset=['Accuracy','Precision','Recall','F1-Score'],\n",
    "                             cmap='Greens')\n",
    "        .set_caption(\"Perbandingan Performa Direct Modeling\"))\n",
    "\n",
    "# ── Visualisasi Grouped Bar Chart ──\n",
    "metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score']\n",
    "x = np.arange(len(metrics))\n",
    "width = 0.25\n",
    "colors = ['#3498db', '#e74c3c', '#2ecc71']  # Biru, Merah, Hijau\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(12, 6))\n",
    "for i, (name, row) in enumerate(results_df.iterrows()):\n",
    "    vals = [row[m] for m in metrics]\n",
    "    bars = ax.bar(x + i*width, vals, width, label=name, color=colors[i],\n",
    "                  edgecolor='black', alpha=0.85)\n",
    "    # Tambahkan label angka di atas setiap bar\n",
    "    for bar, val in zip(bars, vals):\n",
    "        ax.text(bar.get_x() + bar.get_width()/2,\n",
    "                bar.get_height() + 0.005,\n",
    "                f'{val:.3f}', ha='center', fontsize=8, fontweight='bold')\n",
    "\n",
    "ax.set_xlabel('Metrik Evaluasi')\n",
    "ax.set_ylabel('Nilai')\n",
    "ax.set_title('Perbandingan Performa Direct Modeling', fontsize=14, fontweight='bold')\n",
    "ax.set_xticks(x + width)\n",
    "ax.set_xticklabels(metrics)\n",
    "ax.set_ylim(0, 1.1)\n",
    "ax.legend(loc='lower right', fontsize=8)\n",
    "ax.axhline(y=0.5, color='gray', linestyle='--', linewidth=0.8, label='Baseline 0.5')\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 38 — Confusion Matrix (Direct)
# ═══════════════════════════════════════════════════════════════
comments[38] = [
    "# ============================================================\n",
    "# CONFUSION MATRIX — Direct Modeling\n",
    "# ============================================================\n",
    "# Confusion Matrix menunjukkan detail prediksi:\n",
    "#   ┌──────────────┬─────────────────┬───────────────┐\n",
    "#   │              │ Pred: No Churn  │ Pred: Churn   │\n",
    "#   ├──────────────┼─────────────────┼───────────────┤\n",
    "#   │ Act: No Churn│ True Negative   │ False Positive│\n",
    "#   │ Act: Churn   │ False Negative  │ True Positive │\n",
    "#   └──────────────┴─────────────────┴───────────────┘\n",
    "#\n",
    "# YANG PALING PENTING: False Negative (FN)\n",
    "# → Pelanggan yang BENAR churn tapi diprediksi TIDAK churn\n",
    "# → Ini pelanggan yang \"terlewat\" oleh model (berbahaya!)\n",
    "# ============================================================\n",
    "\n",
    "fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
    "short_names = ['Logistic\\nRegression', 'Random\\nForest', 'Voting\\nClassifier']\n",
    "\n",
    "for ax, (name, model), short in zip(axes, models.items(), short_names):\n",
    "    y_pred = model.predict(X_test_d)\n",
    "    cm = confusion_matrix(y_test_d, y_pred)\n",
    "\n",
    "    sns.heatmap(\n",
    "        cm, annot=True, fmt='d', cmap='Blues',\n",
    "        xticklabels=['Pred: No Churn', 'Pred: Churn'],\n",
    "        yticklabels=['Act: No Churn', 'Act: Churn'],\n",
    "        ax=ax, linewidths=0.5\n",
    "    )\n",
    "    acc = accuracy_score(y_test_d, y_pred)\n",
    "    ax.set_title(f'{short}\\nAccuracy: {acc:.4f}', fontsize=11, fontweight='bold')\n",
    "    ax.set_ylabel('Actual')\n",
    "    ax.set_xlabel('Predicted')\n",
    "\n",
    "plt.suptitle('Confusion Matrix — Direct Modeling', fontsize=14, fontweight='bold', y=1.02)\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 40 — Classification Report
# ═══════════════════════════════════════════════════════════════
comments[40] = [
    "# ============================================================\n",
    "# CLASSIFICATION REPORT — Detail per Kelas\n",
    "# ============================================================\n",
    "# Menampilkan Precision, Recall, F1-Score untuk SETIAP kelas:\n",
    "# - Kelas 0 (Tidak Churn)\n",
    "# - Kelas 1 (Churn)\n",
    "# Juga menampilkan macro avg, weighted avg, dan support.\n",
    "# ============================================================\n",
    "\n",
    "for name, model in models.items():\n",
    "    y_pred = model.predict(X_test_d)\n",
    "    print(f\"\\n{'─'*50}\")\n",
    "    print(f\"📌 {name}\")\n",
    "    print(f\"{'─'*50}\")\n",
    "    print(classification_report(y_test_d, y_pred,\n",
    "          target_names=['Tidak Churn (0)', 'Churn (1)']))\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 46 — Salin Dataset (Preprocessing)
# ═══════════════════════════════════════════════════════════════
comments[46] = [
    "# ============================================================\n",
    "# SALIN DATASET — Mulai Tahap Preprocessing\n",
    "# ============================================================\n",
    "# df.copy() membuat salinan INDEPENDEN dari DataFrame asli.\n",
    "# Tujuannya: agar preprocessing TIDAK mengubah data asli (df),\n",
    "# sehingga data asli tetap bisa dipakai untuk perbandingan.\n",
    "# ============================================================\n",
    "\n",
    "df_prep = df.copy()  # Salinan independen (deep copy)\n",
    "\n",
    "print(f\"✅ Dataset berhasil disalin ke df_prep\")\n",
    "print(f\"   Shape awal : {df_prep.shape}\")\n",
    "print(f\"   Kolom      : {list(df_prep.columns)}\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 48 — Drop Fitur Tidak Relevan
# ═══════════════════════════════════════════════════════════════
comments[48] = [
    "# ============================================================\n",
    "# STEP 1 — DROP FITUR TIDAK RELEVAN\n",
    "# ============================================================\n",
    "# Kolom 'coupon_code' di-drop karena:\n",
    "# 1. Missing value 40.89% (terlalu banyak → tidak reliable)\n",
    "# 2. Isinya hanya kode promo (NEW20, REF10, SAVE15)\n",
    "# 3. Tidak mencerminkan perilaku pelanggan secara langsung\n",
    "# 4. Korelasi terhadap churn sangat rendah dari hasil EDA\n",
    "#\n",
    "# CATATAN: customer_id dipertahankan di df_prep untuk sementara\n",
    "# tapi TIDAK akan masuk ke fitur prediktor (X) nanti.\n",
    "# ============================================================\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"     STEP 1 — DROP FITUR TIDAK RELEVAN\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "drop_cols = ['coupon_code']  # Kolom yang akan di-drop\n",
    "df_prep   = df_prep.drop(columns=drop_cols)\n",
    "\n",
    "print(f\"\\n  Kolom yang di-drop : {drop_cols}\")\n",
    "print(f\"\\n  📌 Alasan drop 'coupon_code':\")\n",
    "print(f\"     - Missing value sangat tinggi : 40.89% (6.133 dari 15.000 baris)\")\n",
    "print(f\"     - Isi kolom hanya kode promo  : NEW20, REF10, SAVE15\")\n",
    "print(f\"     - Tidak mencerminkan perilaku pelanggan secara langsung\")\n",
    "print(f\"     - Tidak memiliki nilai prediktif signifikan terhadap churn\")\n",
    "print(f\"     - Berdasarkan analisis korelasi EDA, kontribusinya sangat rendah\")\n",
    "print(f\"\\n  📌 Catatan:\")\n",
    "print(f\"     'customer_id' dipertahankan di df_prep, namun TIDAK akan\")\n",
    "print(f\"     dimasukkan sebagai fitur prediktor (X) karena hanya berfungsi\")\n",
    "print(f\"     sebagai identifier unik pelanggan, bukan atribut prediktif\")\n",
    "print(f\"\\n  Shape setelah drop : {df_prep.shape}\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 50 — Handling Duplicate
# ═══════════════════════════════════════════════════════════════
comments[50] = [
    "# ============================================================\n",
    "# HANDLING DATA DUPLIKAT\n",
    "# ============================================================\n",
    "# Cek apakah ada baris yang 100% identik di semua kolom.\n",
    "# Data duplikat bisa menyebabkan model \"menghafal\" data\n",
    "# dan mengurangi kemampuan generalisasi.\n",
    "# ============================================================\n",
    "\n",
    "jumlah_duplikat = df_prep.duplicated().sum()  # Hitung baris duplikat\n",
    "print(f\"\\n  Jumlah baris duplikat : {jumlah_duplikat}\")\n",
    "\n",
    "if jumlah_duplikat > 0:\n",
    "    df_prep = df_prep.drop_duplicates()  # Hapus duplikat, simpan yang pertama\n",
    "    print(f\"  ✅ {jumlah_duplikat} baris duplikat berhasil dihapus\")\n",
    "else:\n",
    "    print(f\"  ✅ Tidak ada duplikat dalam dataset — tidak ada yang dihapus\")\n",
    "\n",
    "print(f\"\\n  Shape saat ini : {df_prep.shape}\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 52 — Ekstraksi Fitur Datetime
# ═══════════════════════════════════════════════════════════════
comments[52] = [
    "# ============================================================\n",
    "# STEP 3 — EKSTRAKSI FITUR DARI KOLOM DATETIME\n",
    "# ============================================================\n",
    "# Kolom datetime (signup_date, last_purchase_date) tidak bisa\n",
    "# langsung dipakai model ML. Perlu diubah menjadi fitur numerik.\n",
    "#\n",
    "# FITUR BARU yang dibuat:\n",
    "# 1. days_since_last_purchase → Berapa hari sejak beli terakhir\n",
    "#    (semakin lama = semakin berisiko churn)\n",
    "# 2. tenure_days → Lama berlangganan (hari)\n",
    "#    (semakin lama = semakin loyal)\n",
    "# 3. signup_year  → Tahun mendaftar (tren tahunan)\n",
    "# 4. signup_month → Bulan mendaftar (pola musiman)\n",
    "# ============================================================\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"     STEP 3 — EKSTRAKSI FITUR DATETIME\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "# Konversi string ke tipe datetime agar bisa dihitung selisihnya\n",
    "df_prep['signup_date']        = pd.to_datetime(df_prep['signup_date'])\n",
    "df_prep['last_purchase_date'] = pd.to_datetime(df_prep['last_purchase_date'])\n",
    "\n",
    "# Tanggal referensi = transaksi paling baru di dataset\n",
    "ref_date = df_prep['last_purchase_date'].max()\n",
    "print(f\"\\n  Tanggal referensi : {ref_date.date()}\")\n",
    "\n",
    "# Buat 4 fitur baru dari kolom datetime\n",
    "df_prep['days_since_last_purchase'] = (ref_date - df_prep['last_purchase_date']).dt.days  # Recency\n",
    "df_prep['tenure_days']              = (df_prep['last_purchase_date'] - df_prep['signup_date']).dt.days  # Lama langganan\n",
    "df_prep['signup_year']              = df_prep['signup_date'].dt.year   # Tahun daftar\n",
    "df_prep['signup_month']             = df_prep['signup_date'].dt.month  # Bulan daftar\n",
    "\n",
    "# Hapus kolom datetime asli (sudah di-extract ke fitur baru)\n",
    "df_prep = df_prep.drop(columns=['signup_date', 'last_purchase_date'])\n",
    "\n",
    "print(f\"\\n  📌 Fitur baru yang dibuat:\")\n",
    "print(f\"  {'Fitur':<30} Keterangan\")\n",
    "print(f\"  {'─'*65}\")\n",
    "print(f\"  {'days_since_last_purchase':<30} Jumlah hari sejak transaksi terakhir\")\n",
    "print(f\"  {'tenure_days':<30} Lama berlangganan dalam hari\")\n",
    "print(f\"  {'signup_year':<30} Tahun pelanggan mendaftar\")\n",
    "print(f\"  {'signup_month':<30} Bulan pelanggan mendaftar\")\n",
    "print(f\"\\n  Kolom datetime asli → di-drop\")\n",
    "print(f\"  Shape setelah ekstraksi : {df_prep.shape}\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 54 — Handling Missing Value
# ═══════════════════════════════════════════════════════════════
comments[54] = [
    "# ============================================================\n",
    "# STEP 4 — PENANGANAN MISSING VALUE\n",
    "# ============================================================\n",
    "# STRATEGI IMPUTASI (mengisi, bukan menghapus):\n",
    "# - age               → Median (karena ada outlier/negatif)\n",
    "# - total_spent       → Median (distribusi skewed/miring)\n",
    "# - satisfaction_score → Median (skala ordinal 1-5)\n",
    "# - gender            → Modus (kategorikal → isi nilai terbanyak)\n",
    "#\n",
    "# MENGAPA IMPUTASI bukan DROP baris?\n",
    "# → Drop baris akan menghilangkan ratusan data berharga\n",
    "# → Informasi di kolom LAIN pada baris tersebut tetap berguna\n",
    "# → Median & modus robust terhadap distribusi tidak normal\n",
    "# ============================================================\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"      STEP 4 — PENANGANAN MISSING VALUE\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "# Cek kondisi missing value sebelum penanganan\n",
    "print(\"\\n  Missing Value sebelum penanganan:\")\n",
    "mv_before = df_prep.isnull().sum()\n",
    "mv_before = mv_before[mv_before > 0]\n",
    "print(mv_before.to_string())\n",
    "\n",
    "# Imputasi: isi nilai NaN dengan strategi yang sesuai\n",
    "df_prep['age']                = df_prep['age'].fillna(df_prep['age'].median())                # Numerik → Median\n",
    "df_prep['total_spent']        = df_prep['total_spent'].fillna(df_prep['total_spent'].median()) # Numerik → Median\n",
    "df_prep['satisfaction_score'] = df_prep['satisfaction_score'].fillna(df_prep['satisfaction_score'].median()) # Ordinal → Median\n",
    "df_prep['gender']             = df_prep['gender'].fillna(df_prep['gender'].mode()[0])          # Kategorikal → Modus\n",
    "\n",
    "# Ringkasan strategi yang digunakan\n",
    "print(f\"\\n  📌 Strategi Imputasi:\")\n",
    "print(f\"  {'Kolom':<22} {'Metode':<8} Alasan\")\n",
    "print(f\"  {'─'*72}\")\n",
    "print(f\"  {'age':<22} {'Median':<8} Numerik, ada outlier & nilai negatif → median lebih stabil\")\n",
    "print(f\"  {'total_spent':<22} {'Median':<8} Numerik, distribusi skewed → median lebih robust dari mean\")\n",
    "print(f\"  {'satisfaction_score':<22} {'Median':<8} Skala ordinal 1–5, median lebih representatif\")\n",
    "print(f\"  {'gender':<22} {'Modus':<8} Kategorikal → diisi nilai yang paling sering muncul\")\n",
    "\n",
    "print(f\"\\n  📌 Kenapa IMPUTASI bukan DROP baris?\")\n",
    "print(f\"     → Drop baris akan menghilangkan ratusan data berharga\")\n",
    "print(f\"     → Imputasi mempertahankan informasi kolom lain pada baris tersebut\")\n",
    "print(f\"     → Median & modus robust terhadap distribusi tidak normal\")\n",
    "\n",
    "mv_after = df_prep.isnull().sum().sum()\n",
    "print(f\"\\n  Total missing value tersisa : {mv_after}\")\n",
    "print(f\"  ✅ Semua missing value berhasil ditangani!\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 56 — Handling Outlier
# ═══════════════════════════════════════════════════════════════
comments[56] = [
    "# ============================================================\n",
    "# STEP 5 — PENANGANAN OUTLIER (IQR Clipping)\n",
    "# ============================================================\n",
    "# METODE: IQR (Interquartile Range) Clipping\n",
    "#   - Q1 = kuartil 25%, Q3 = kuartil 75%\n",
    "#   - IQR = Q3 - Q1\n",
    "#   - Batas bawah = Q1 - 1.5 × IQR\n",
    "#   - Batas atas  = Q3 + 1.5 × IQR\n",
    "#   - Nilai di luar batas → di-CLIP (diubah ke batas terdekat)\n",
    "#\n",
    "# MENGAPA CLIP bukan DROP?\n",
    "# → Clip mempertahankan jumlah data (tidak ada yang hilang)\n",
    "# → Hanya nilai ekstrem yang diubah ke batas wajar\n",
    "# → Lebih aman untuk dataset yang ukurannya terbatas\n",
    "#\n",
    "# KHUSUS AGE: Usia negatif (< 0) dihapus karena tidak valid\n",
    "# ============================================================\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"       STEP 5 — PENANGANAN OUTLIER\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "# Daftar kolom yang akan ditangani outliernya\n",
    "outlier_cols = [\n",
    "    'age', 'total_spent', 'avg_session_time',\n",
    "    'pages_per_session', 'avg_order_value',\n",
    "    'marketing_spend_per_user', 'lifetime_value',\n",
    "    'days_since_last_purchase', 'tenure_days'\n",
    "]\n",
    "\n",
    "print(f\"\\n  Shape sebelum : {df_prep.shape}\")\n",
    "\n",
    "# Khusus age: filter nilai negatif terlebih dahulu (data invalid)\n",
    "n_age_invalid = (df_prep['age'] < 0).sum()\n",
    "df_prep = df_prep[df_prep['age'] >= 0]\n",
    "print(f\"\\n  ⚠️  Ditemukan {n_age_invalid} data age < 0 (tidak valid) → dihapus\")\n",
    "\n",
    "# Deteksi & Clipping menggunakan metode IQR\n",
    "print(f\"\\n  📌 Deteksi Outlier per Kolom (IQR Method):\")\n",
    "print(f\"  {'Kolom':<30} {'Outlier':>8}  {'Batas Bawah':>12}  {'Batas Atas':>12}\")\n",
    "print(f\"  {'─'*68}\")\n",
    "\n",
    "for col in outlier_cols:\n",
    "    Q1    = df_prep[col].quantile(0.25)   # Kuartil 1 (25%)\n",
    "    Q3    = df_prep[col].quantile(0.75)   # Kuartil 3 (75%)\n",
    "    IQR   = Q3 - Q1                       # Interquartile Range\n",
    "    lower = Q1 - 1.5 * IQR               # Batas bawah\n",
    "    upper = Q3 + 1.5 * IQR               # Batas atas\n",
    "    n_out = ((df_prep[col] < lower) | (df_prep[col] > upper)).sum()  # Jumlah outlier\n",
    "    print(f\"  {col:<30} {n_out:>8}  {lower:>12.2f}  {upper:>12.2f}\")\n",
    "    df_prep[col] = df_prep[col].clip(lower=lower, upper=upper)  # Clip ke batas\n",
    "\n",
    "print(f\"\\n  📌 Metode  : IQR Clipping (Q1-1.5×IQR s/d Q3+1.5×IQR)\")\n",
    "print(f\"  📌 Alasan  : Clip lebih aman daripada drop agar data tidak banyak berkurang\")\n",
    "print(f\"\\n  Shape setelah : {df_prep.shape}\")\n",
    "print(f\"  ✅ Outlier berhasil ditangani!\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 58 — Boxplot Setelah Outlier
# ═══════════════════════════════════════════════════════════════
comments[58] = [
    "# ============================================================\n",
    "# VISUALISASI BOXPLOT SETELAH PENANGANAN OUTLIER\n",
    "# ============================================================\n",
    "# Membandingkan distribusi fitur numerik SETELAH clipping.\n",
    "# Seharusnya tidak ada lagi titik-titik outlier yang ekstrem.\n",
    "# ============================================================\n",
    "\n",
    "vis_cols = ['age', 'total_spent', 'avg_session_time',\n",
    "            'avg_order_value', 'lifetime_value', 'days_since_last_purchase']\n",
    "titles   = ['Age', 'Total Spent', 'Avg Session Time',\n",
    "            'Avg Order Value', 'Lifetime Value', 'Days Since Last Purchase']\n",
    "\n",
    "fig, axes = plt.subplots(2, 3, figsize=(16, 10))\n",
    "axes = axes.flatten()\n",
    "\n",
    "for i, (col, title) in enumerate(zip(vis_cols, titles)):\n",
    "    axes[i].boxplot(\n",
    "        df_prep[col], patch_artist=True,\n",
    "        boxprops=dict(facecolor='#3498db', color='navy'),\n",
    "        medianprops=dict(color='red', linewidth=2),\n",
    "        whiskerprops=dict(color='navy'),\n",
    "        capprops=dict(color='navy')\n",
    "    )\n",
    "    axes[i].set_title(f'{title}', fontsize=11, fontweight='bold')\n",
    "    axes[i].set_ylabel('Nilai')\n",
    "\n",
    "plt.suptitle('Distribusi Fitur Numerik Setelah Penanganan Outlier',\n",
    "             fontsize=14, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 60 — Encoding Fitur Kategorikal
# ═══════════════════════════════════════════════════════════════
comments[60] = [
    "# ============================================================\n",
    "# STEP 6 — ENCODING FITUR KATEGORIKAL\n",
    "# ============================================================\n",
    "# Model ML hanya bisa menerima input NUMERIK. Fitur kategorikal\n",
    "# (tipe object/string) perlu diubah menjadi angka.\n",
    "#\n",
    "# STRATEGI ENCODING:\n",
    "# 1. Label Encoding → untuk kolom dengan ≤2 nilai unik (binary)\n",
    "#    Contoh: subscription_type (Annual=0, Monthly=1)\n",
    "#\n",
    "# 2. One-Hot Encoding → untuk kolom dengan >2 nilai unik\n",
    "#    Contoh: gender (Male, Female, Other) → 2 kolom baru\n",
    "#    drop_first=True → hindari \"dummy variable trap\" dengan\n",
    "#    hanya membuat n-1 kolom (kelas pertama jadi referensi)\n",
    "# ============================================================\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"      STEP 6 — ENCODING FITUR KATEGORIKAL\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "\n",
    "# Deteksi kolom bertipe object (kategorikal)\n",
    "cat_cols = df_prep.select_dtypes(include='object').columns.tolist()\n",
    "print(f\"\\n  Kolom kategorikal terdeteksi : {cat_cols}\")\n",
    "\n",
    "# Pisahkan menjadi binary (≤2 nilai) dan multi-kelas (>2 nilai)\n",
    "binary_cols = []\n",
    "onehot_cols = []\n",
    "\n",
    "for col in cat_cols:\n",
    "    n = df_prep[col].nunique()  # Jumlah nilai unik\n",
    "    if n <= 2:\n",
    "        binary_cols.append(col)   # → Label Encoding\n",
    "    else:\n",
    "        onehot_cols.append(col)   # → One-Hot Encoding\n",
    "\n",
    "print(f\"\\n  📌 Label Encoding   (≤2 nilai unik) : {binary_cols}\")\n",
    "print(f\"  📌 One-Hot Encoding (>2 nilai unik) : {onehot_cols}\")\n",
    "\n",
    "# Label Encoding untuk kolom binary\n",
    "le = LabelEncoder()\n",
    "for col in binary_cols:\n",
    "    df_prep[col] = le.fit_transform(df_prep[col])\n",
    "    print(f\"\\n  ✅ Label Encoded  : '{col}'\")\n",
    "\n",
    "# One-Hot Encoding untuk kolom multi-kelas\n",
    "# drop_first=True → hindari multikolinearitas\n",
    "df_prep = pd.get_dummies(df_prep, columns=onehot_cols, drop_first=True)\n",
    "print(f\"\\n  ✅ One-Hot Encoded : {onehot_cols}\")\n",
    "\n",
    "# Konversi kolom boolean hasil One-Hot ke integer (0/1)\n",
    "bool_cols = df_prep.select_dtypes(include='bool').columns\n",
    "df_prep[bool_cols] = df_prep[bool_cols].astype(int)\n",
    "\n",
    "print(f\"\\n  Shape setelah encoding : {df_prep.shape}\")\n",
    "print(f\"  ✅ Semua fitur kategorikal berhasil di-encode!\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 62 — Ringkasan Preprocessing
# ═══════════════════════════════════════════════════════════════
comments[62] = [
    "# ============================================================\n",
    "# RINGKASAN HASIL PREPROCESSING\n",
    "# ============================================================\n",
    "# Menampilkan semua kolom hasil preprocessing beserta tipe\n",
    "# datanya untuk memastikan semua sudah numerik dan siap\n",
    "# digunakan untuk training model.\n",
    "# ============================================================\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"        RINGKASAN HASIL PREPROCESSING\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "print(f\"\\n  Shape awal   : (15.000, 30)\")\n",
    "print(f\"  Shape akhir  : {df_prep.shape}\")\n",
    "print(f\"  Missing value tersisa : {df_prep.isnull().sum().sum()}\")\n",
    "\n",
    "print(f\"\\n  Semua kolom setelah preprocessing ({df_prep.shape[1]} kolom):\")\n",
    "print(f\"  {'No':<4} {'Kolom':<45} {'Dtype'}\")\n",
    "print(f\"  {'─'*65}\")\n",
    "for i, col in enumerate(df_prep.columns, 1):\n",
    "    print(f\"  {i:<4} {col:<45} {df_prep[col].dtype}\")\n",
    "\n",
    "print(f\"\\n  ✅ Data siap untuk modeling!\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 64 — Tetapkan X dan y
# ═══════════════════════════════════════════════════════════════
comments[64] = [
    "# ============================================================\n",
    "# PENETAPAN FITUR (X) DAN TARGET (y)\n",
    "# ============================================================\n",
    "# X = semua kolom KECUALI 'churn' dan 'customer_id'\n",
    "# y = kolom 'churn' (target yang ingin diprediksi)\n",
    "#\n",
    "# customer_id di-exclude karena hanya identifier unik,\n",
    "# bukan fitur prediktif (tidak ada hubungan dengan churn).\n",
    "# ============================================================\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"       PENETAPAN FITUR (X) DAN TARGET (y)\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "# Pisahkan fitur dan target\n",
    "X_prep = df_prep.drop(columns=['churn', 'customer_id'])  # Fitur prediktor\n",
    "y_prep = df_prep['churn']                                 # Target (0/1)\n",
    "\n",
    "print(f\"\\n  📌 Kolom yang dikeluarkan dari X:\")\n",
    "print(f\"     - 'churn'       : variabel target (y)\")\n",
    "print(f\"     - 'customer_id' : hanya ID unik, bukan fitur prediktif\")\n",
    "\n",
    "print(f\"\\n  Jumlah fitur prediktor (X) : {X_prep.shape[1]} kolom\")\n",
    "print(f\"  Jumlah data (y)            : {y_prep.shape[0]:,} baris\")\n",
    "\n",
    "print(f\"\\n  📌 Distribusi Target (y):\")\n",
    "print(f\"     Tidak Churn (0) : {(y_prep==0).sum():,} ({(y_prep==0).mean()*100:.2f}%)\")\n",
    "print(f\"     Churn       (1) : {(y_prep==1).sum():,} ({(y_prep==1).mean()*100:.2f}%)\")\n",
    "\n",
    "print(f\"\\n  📌 Daftar Fitur X ({X_prep.shape[1]} kolom):\")\n",
    "for i, col in enumerate(X_prep.columns, 1):\n",
    "    print(f\"     {i:>2}. {col}\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 66 — Train Test Split (Preprocessing)
# ═══════════════════════════════════════════════════════════════
comments[66] = [
    "# ============================================================\n",
    "# TRAIN TEST SPLIT — Data Hasil Preprocessing\n",
    "# ============================================================\n",
    "# Sama seperti Direct Modeling: 80% train, 20% test\n",
    "# Bedanya: data ini sudah melalui preprocessing lengkap\n",
    "# (cleaning, feature engineering, encoding)\n",
    "# ============================================================\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "X_train_p, X_test_p, y_train_p, y_test_p = train_test_split(\n",
    "    X_prep, y_prep,\n",
    "    test_size=0.2,       # 20% untuk testing\n",
    "    random_state=42,     # Seed sama agar fair dalam perbandingan\n",
    "    stratify=y_prep      # Stratify → proporsi churn terjaga\n",
    ")\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"              TRAIN TEST SPLIT\")\n",
    "print(\"=\" * 60)\n",
    "print(f\"\\n  Total data    : {len(X_prep):,}\")\n",
    "print(f\"  Data latih    : {len(X_train_p):,} (80%)\")\n",
    "print(f\"  Data uji      : {len(X_test_p):,}  (20%)\")\n",
    "print(f\"  Random state  : 42\")\n",
    "print(f\"  Stratify      : ✅ (proporsi churn seimbang di train & test)\")\n",
    "\n",
    "print(f\"\\n  📌 Distribusi y_train:\")\n",
    "print(f\"     Tidak Churn (0) : {(y_train_p==0).sum():,} ({(y_train_p==0).mean()*100:.2f}%)\")\n",
    "print(f\"     Churn       (1) : {(y_train_p==1).sum():,} ({(y_train_p==1).mean()*100:.2f}%)\")\n",
    "\n",
    "print(f\"\\n  📌 Distribusi y_test:\")\n",
    "print(f\"     Tidak Churn (0) : {(y_test_p==0).sum():,} ({(y_test_p==0).mean()*100:.2f}%)\")\n",
    "print(f\"     Churn       (1) : {(y_test_p==1).sum():,} ({(y_test_p==1).mean()*100:.2f}%)\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 68 — Scaling
# ═══════════════════════════════════════════════════════════════
comments[68] = [
    "# ============================================================\n",
    "# SCALING FITUR — StandardScaler (Z-Score Normalization)\n",
    "# ============================================================\n",
    "# RUMUS: z = (x - μ) / σ → mean=0, std=1\n",
    "#\n",
    "# MENGAPA perlu scaling?\n",
    "# - Logistic Regression sensitif terhadap perbedaan skala fitur\n",
    "# - SVM (di VotingClassifier) sangat sensitif terhadap skala\n",
    "# - Random Forest tidak sensitif, tapi scaling tidak merugikan\n",
    "#\n",
    "# PENTING — CEGAH DATA LEAKAGE:\n",
    "# - fit_transform(X_train) → scaler belajar mean & std dari TRAIN saja\n",
    "# - transform(X_test)      → test di-scale pakai parameter dari train\n",
    "# - ❌ JANGAN fit_transform(X_test)! Itu data leakage!\n",
    "# ============================================================\n",
    "\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "scaler = StandardScaler()\n",
    "\n",
    "X_train_p = scaler.fit_transform(X_train_p)  # fit + transform → hanya TRAIN\n",
    "X_test_p  = scaler.transform(X_test_p)        # transform saja  → TEST\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"               SCALING FITUR\")\n",
    "print(\"=\" * 60)\n",
    "print(f\"\\n  Metode  : StandardScaler (z-score normalization)\")\n",
    "print(f\"  Formula : z = (x - μ) / σ  →  mean=0, std=1\")\n",
    "print(f\"\\n  📌 Alasan menggunakan StandardScaler:\")\n",
    "print(f\"     - Logistic Regression sensitif terhadap perbedaan skala fitur\")\n",
    "print(f\"     - SVM (dalam VotingClassifier) sangat sensitif terhadap skala\")\n",
    "print(f\"     - Random Forest tidak sensitif, namun tidak dirugikan oleh scaling\")\n",
    "print(f\"\\n  📌 Proses (cegah data leakage):\")\n",
    "print(f\"     - fit_transform(X_train) → scaler belajar mean & std dari TRAIN saja\")\n",
    "print(f\"     - transform(X_test)      → test di-scale pakai parameter dari train\")\n",
    "print(f\"     ✅ Tidak ada informasi test set yang bocor ke proses training!\")\n",
    "print(f\"\\n  Shape X_train : {X_train_p.shape}\")\n",
    "print(f\"  Shape X_test  : {X_test_p.shape}\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 72 — Training Model Preprocessing
# ═══════════════════════════════════════════════════════════════
comments[72] = [
    "# ============================================================\n",
    "# TRAINING MODEL — Dengan Data Hasil Preprocessing\n",
    "# ============================================================\n",
    "# 3 model yang SAMA dengan Direct Modeling:\n",
    "# 1. Logistic Regression\n",
    "# 2. Random Forest\n",
    "# 3. Voting Classifier (LR + SVM + KNN)\n",
    "#\n",
    "# BEDANYA dari Bagian 2:\n",
    "# - Data sudah di-preprocessing (cleaning, encoding, scaling)\n",
    "# - Fitur lebih lengkap (termasuk fitur datetime & kategorikal)\n",
    "#\n",
    "# BELUM ada hyperparameter tuning (pakai default parameter)\n",
    "# → Agar perbandingan antar skenario bersifat ADIL\n",
    "# ============================================================\n",
    "\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.ensemble import RandomForestClassifier, VotingClassifier\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.metrics import (accuracy_score, precision_score,\n",
    "                              recall_score, f1_score,\n",
    "                              confusion_matrix, classification_report)\n",
    "import time\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"             TRAINING MODEL\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "# Inisialisasi 3 model (parameter default)\n",
    "model_lr_p     = LogisticRegression(random_state=42, max_iter=1000)\n",
    "model_rf_p     = RandomForestClassifier(random_state=42)\n",
    "model_voting_p = VotingClassifier(\n",
    "    estimators=[\n",
    "        ('lr',  LogisticRegression(random_state=42, max_iter=1000)),\n",
    "        ('svm', SVC(probability=True, random_state=42)),\n",
    "        ('knn', KNeighborsClassifier())\n",
    "    ],\n",
    "    voting='soft'  # Rata-rata probabilitas dari 3 model\n",
    ")\n",
    "\n",
    "models_prep = {\n",
    "    'Logistic Regression (Konvensional)' : model_lr_p,\n",
    "    'Random Forest (Ensemble Bagging)'   : model_rf_p,\n",
    "    'Voting Classifier (LR + SVM + KNN)' : model_voting_p\n",
    "}\n",
    "\n",
    "results_prep = {}  # Simpan hasil evaluasi\n",
    "\n",
    "# Loop training & evaluasi untuk setiap model\n",
    "for name, model in models_prep.items():\n",
    "    print(f\"\\n  ⏳ Melatih : {name}...\")\n",
    "    start    = time.time()\n",
    "    model.fit(X_train_p, y_train_p)    # Training\n",
    "    duration = time.time() - start\n",
    "    y_pred   = model.predict(X_test_p)  # Prediksi\n",
    "\n",
    "    # Evaluasi 4 metrik\n",
    "    acc  = accuracy_score(y_test_p, y_pred)\n",
    "    prec = precision_score(y_test_p, y_pred)\n",
    "    rec  = recall_score(y_test_p, y_pred)\n",
    "    f1   = f1_score(y_test_p, y_pred)\n",
    "\n",
    "    results_prep[name] = {\n",
    "        'Accuracy' : acc,\n",
    "        'Precision': prec,\n",
    "        'Recall'   : rec,\n",
    "        'F1-Score' : f1,\n",
    "        'Waktu (s)': round(duration, 2)\n",
    "    }\n",
    "    print(f\"  ✅ Selesai {duration:.2f}s | Acc: {acc:.4f} | \"\n",
    "          f\"Prec: {prec:.4f} | Rec: {rec:.4f} | F1: {f1:.4f}\")\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 82 — Feature Importance
# ═══════════════════════════════════════════════════════════════
comments[82] = [
    "# ============================================================\n",
    "# STEP 1 — ANALISIS FEATURE IMPORTANCE\n",
    "# ============================================================\n",
    "# TUJUAN: Mengetahui fitur mana yang PALING BERPENGARUH\n",
    "# terhadap prediksi churn berdasarkan Random Forest.\n",
    "#\n",
    "# CARA KERJA:\n",
    "# - Random Forest menghitung \"importance\" setiap fitur\n",
    "# - Diukur dari seberapa besar fitur tersebut mengurangi\n",
    "#   impurity (Gini) saat splitting di Decision Tree\n",
    "# - Semakin tinggi score → semakin penting fiturnya\n",
    "#\n",
    "# KEGUNAAN:\n",
    "# - Memahami faktor utama penyebab churn\n",
    "# - Membantu tim bisnis fokus pada area yang tepat\n",
    "# - Referensi untuk feature selection di tuning\n",
    "# ============================================================\n",
    "\n",
    "print('=' * 60)\n",
    "print('       STEP 1 — ANALISIS FEATURE IMPORTANCE')\n",
    "print('=' * 60)\n",
    "\n",
    "import time\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# Ambil feature importance dari Random Forest yang sudah ditraining\n",
    "feature_names = X_prep.columns.tolist()          # Nama semua fitur\n",
    "importances   = model_rf_p.feature_importances_  # Skor importance\n",
    "indices       = np.argsort(importances)[::-1]    # Urutkan descending\n",
    "\n",
    "# Buat DataFrame untuk kemudahan analisis\n",
    "fi_df = pd.DataFrame({\n",
    "    'Fitur'      : [feature_names[i] for i in indices],\n",
    "    'Importance' : importances[indices]\n",
    "})\n",
    "\n",
    "# Tampilkan tabel Top 20 fitur terpenting\n",
    "print(f'\\n  Total fitur : {len(feature_names)}')\n",
    "print(f'\\n  📌 Top 20 Fitur Terpenting:')\n",
    "print(f'\\n  {\"Rank\":<6} {\"Fitur\":<45} {\"Importance\":>12}')\n",
    "print(f'  {\"─\"*65}')\n",
    "for i, row in fi_df.head(20).iterrows():\n",
    "    bar = '█' * int(row['Importance'] * 200)  # Visual bar sederhana\n",
    "    print(f'  {i+1:<6} {row[\"Fitur\"]:<45} {row[\"Importance\"]:>10.4f}  {bar}')\n",
    "\n",
    "# ── Visualisasi Horizontal Bar Chart ──\n",
    "fig, ax = plt.subplots(figsize=(12, 8))\n",
    "colors  = ['#e74c3c' if i < 5 else '#3498db' if i < 10 else '#95a5a6'\n",
    "           for i in range(20)]  # Merah=top 5, Biru=top 6-10, Abu=sisanya\n",
    "\n",
    "bars = ax.barh(\n",
    "    fi_df['Fitur'].head(20)[::-1],\n",
    "    fi_df['Importance'].head(20)[::-1],\n",
    "    color=colors[::-1], edgecolor='black', alpha=0.85\n",
    ")\n",
    "for bar, val in zip(bars, fi_df['Importance'].head(20)[::-1]):\n",
    "    ax.text(bar.get_width() + 0.001, bar.get_y() + bar.get_height()/2,\n",
    "            f'{val:.4f}', va='center', fontsize=9)\n",
    "\n",
    "ax.set_xlabel('Feature Importance Score')\n",
    "ax.set_title('Top 20 Feature Importance — Random Forest',\n",
    "             fontsize=13, fontweight='bold')\n",
    "ax.axvline(x=fi_df['Importance'].mean(), color='red',\n",
    "           linestyle='--', linewidth=1.5,\n",
    "           label=f'Mean = {fi_df[\"Importance\"].mean():.4f}')\n",
    "ax.legend()\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "top_features = fi_df['Fitur'].head(20).tolist()\n",
    "print(f'\\n  ✅ Top 20 fitur tersimpan untuk referensi tuning')\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 84 — Tuning Logistic Regression
# ═══════════════════════════════════════════════════════════════
comments[84] = [
    "# ============================================================\n",
    "# TUNING 1 — LOGISTIC REGRESSION (RandomizedSearchCV)\n",
    "# ============================================================\n",
    "# METODE: RandomizedSearchCV\n",
    "# → Lebih efisien dari GridSearchCV karena TIDAK mencoba SEMUA\n",
    "#   kombinasi, melainkan sampling acak dari parameter space\n",
    "#\n",
    "# PARAMETER YANG DI-TUNING:\n",
    "# - C            : Kekuatan regularisasi (semakin kecil = semakin kuat)\n",
    "# - penalty      : Tipe regularisasi (L1=Lasso, L2=Ridge)\n",
    "# - solver       : Algoritma optimasi (liblinear, saga)\n",
    "# - max_iter     : Jumlah iterasi maksimum\n",
    "# - class_weight : None atau 'balanced' (untuk handle imbalanced data)\n",
    "#\n",
    "# SCORING: F1-Score → metrik utama kita (karena data imbalanced)\n",
    "# CV: 5-fold cross-validation → hasil lebih stabil\n",
    "# ============================================================\n",
    "\n",
    "from sklearn.model_selection import RandomizedSearchCV\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "\n",
    "print('=' * 60)\n",
    "print('    TUNING 1 — LOGISTIC REGRESSION')\n",
    "print('=' * 60)\n",
    "\n",
    "# Definisikan ruang pencarian parameter\n",
    "param_grid_lr = {\n",
    "    'C'           : [0.001, 0.01, 0.1, 1, 10, 100],  # Regularization strength\n",
    "    'penalty'     : ['l1', 'l2'],                      # L1 (sparse) vs L2 (ridge)\n",
    "    'solver'      : ['liblinear', 'saga'],             # Solver yang support L1\n",
    "    'max_iter'    : [500, 1000, 2000],                 # Max iterasi konvergensi\n",
    "    'class_weight': [None, 'balanced']                 # balanced → kompensasi imbalance\n",
    "}\n",
    "\n",
    "print(f'\\n  📌 Parameter Grid:')\n",
    "for k, v in param_grid_lr.items():\n",
    "    print(f'     {k:<15} : {v}')\n",
    "\n",
    "# Jalankan RandomizedSearchCV\n",
    "rs_lr = RandomizedSearchCV(\n",
    "    estimator           = LogisticRegression(random_state=42),\n",
    "    param_distributions = param_grid_lr,\n",
    "    n_iter              = 30,    # Coba 30 kombinasi acak\n",
    "    cv                  = 5,     # 5-fold cross validation\n",
    "    scoring             = 'f1',  # Optimasi berdasarkan F1-Score\n",
    "    random_state        = 42,\n",
    "    n_jobs              = -1,    # Pakai semua CPU core\n",
    "    verbose             = 0\n",
    ")\n",
    "\n",
    "print(f'\\n  ⏳ Menjalankan RandomizedSearchCV (n_iter=30, cv=5)...')\n",
    "start = time.time()\n",
    "rs_lr.fit(X_train_p, y_train_p)\n",
    "duration = time.time() - start\n",
    "\n",
    "print(f'  ✅ Selesai dalam {duration:.2f} detik')\n",
    "print(f'\\n  📌 Best Parameters:')\n",
    "for k, v in rs_lr.best_params_.items():\n",
    "    print(f'     {k:<15} : {v}')\n",
    "print(f'\\n  Best CV F1-Score : {rs_lr.best_score_:.4f}')\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 85 — Tuning Random Forest
# ═══════════════════════════════════════════════════════════════
comments[85] = [
    "# ============================================================\n",
    "# TUNING 2 — RANDOM FOREST (RandomizedSearchCV)\n",
    "# ============================================================\n",
    "# PARAMETER YANG DI-TUNING:\n",
    "# - n_estimators      : Jumlah pohon (100-500)\n",
    "# - max_depth          : Kedalaman maksimal pohon (kontrol overfitting)\n",
    "# - min_samples_split  : Min sampel untuk split node\n",
    "# - min_samples_leaf   : Min sampel di daun (leaf)\n",
    "# - max_features       : Jumlah fitur per split (sqrt/log2)\n",
    "# - class_weight       : balanced → kompensasi data imbalanced\n",
    "# ============================================================\n",
    "\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "\n",
    "print('=' * 60)\n",
    "print('      TUNING 2 — RANDOM FOREST')\n",
    "print('=' * 60)\n",
    "\n",
    "param_grid_rf = {\n",
    "    'n_estimators'     : [100, 200, 300, 500],  # Jumlah Decision Tree\n",
    "    'max_depth'        : [None, 5, 10, 15, 20], # None = tak terbatas\n",
    "    'min_samples_split': [2, 5, 10],            # Min data untuk split\n",
    "    'min_samples_leaf' : [1, 2, 4],             # Min data di daun\n",
    "    'max_features'     : ['sqrt', 'log2'],      # Fitur per split\n",
    "    'class_weight'     : [None, 'balanced']      # Handle imbalanced\n",
    "}\n",
    "\n",
    "print(f'\\n  📌 Parameter Grid:')\n",
    "for k, v in param_grid_rf.items():\n",
    "    print(f'     {k:<20} : {v}')\n",
    "\n",
    "rs_rf = RandomizedSearchCV(\n",
    "    estimator           = RandomForestClassifier(random_state=42),\n",
    "    param_distributions = param_grid_rf,\n",
    "    n_iter              = 30,    # 30 kombinasi acak\n",
    "    cv                  = 5,     # 5-fold CV\n",
    "    scoring             = 'f1',  # Optimasi F1-Score\n",
    "    random_state        = 42,\n",
    "    n_jobs              = -1,\n",
    "    verbose             = 0\n",
    ")\n",
    "\n",
    "print(f'\\n  ⏳ Menjalankan RandomizedSearchCV (n_iter=30, cv=5)...')\n",
    "start = time.time()\n",
    "rs_rf.fit(X_train_p, y_train_p)\n",
    "duration = time.time() - start\n",
    "\n",
    "print(f'  ✅ Selesai dalam {duration:.2f} detik')\n",
    "print(f'\\n  📌 Best Parameters:')\n",
    "for k, v in rs_rf.best_params_.items():\n",
    "    print(f'     {k:<20} : {v}')\n",
    "print(f'\\n  Best CV F1-Score : {rs_rf.best_score_:.4f}')\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 86 — Tuning Voting Classifier
# ═══════════════════════════════════════════════════════════════
comments[86] = [
    "# ============================================================\n",
    "# TUNING 3 — VOTING CLASSIFIER (RandomizedSearchCV)\n",
    "# ============================================================\n",
    "# Voting Classifier = gabungan LR + SVM + KNN\n",
    "# Tuning dilakukan pada parameter INTERNAL masing-masing model:\n",
    "# - lr__C, lr__max_iter   → parameter Logistic Regression\n",
    "# - svm__C, svm__kernel   → parameter SVM\n",
    "# - knn__n_neighbors, knn__weights → parameter KNN\n",
    "#\n",
    "# n_iter=20 (lebih sedikit karena proses lebih lambat —\n",
    "# harus melatih 3 model per iterasi)\n",
    "# ============================================================\n",
    "\n",
    "from sklearn.ensemble import VotingClassifier\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "\n",
    "print('=' * 60)\n",
    "print('     TUNING 3 — VOTING CLASSIFIER')\n",
    "print('=' * 60)\n",
    "\n",
    "# Parameter grid untuk sub-model dalam Voting Classifier\n",
    "param_grid_voting = {\n",
    "    'lr__C'            : [0.01, 0.1, 1, 10],       # Regularisasi LR\n",
    "    'lr__max_iter'     : [500, 1000],                # Max iterasi LR\n",
    "    'svm__C'           : [0.1, 1, 10],              # Regularisasi SVM\n",
    "    'svm__kernel'      : ['rbf', 'linear'],          # Kernel SVM\n",
    "    'knn__n_neighbors' : [3, 5, 7, 11],             # Jumlah tetangga KNN\n",
    "    'knn__weights'     : ['uniform', 'distance']     # Bobot: seragam/jarak\n",
    "}\n",
    "\n",
    "print(f'\\n  📌 Parameter Grid:')\n",
    "for k, v in param_grid_voting.items():\n",
    "    print(f'     {k:<25} : {v}')\n",
    "\n",
    "# Definisi estimator untuk Voting Classifier\n",
    "voting_estimators = [\n",
    "    ('lr',  LogisticRegression(random_state=42)),\n",
    "    ('svm', SVC(probability=True, random_state=42)),\n",
    "    ('knn', KNeighborsClassifier())\n",
    "]\n",
    "voting_clf = VotingClassifier(estimators=voting_estimators, voting='soft')\n",
    "\n",
    "rs_voting = RandomizedSearchCV(\n",
    "    estimator           = voting_clf,\n",
    "    param_distributions = param_grid_voting,\n",
    "    n_iter              = 20,    # 20 kombinasi (lebih lambat)\n",
    "    cv                  = 5,\n",
    "    scoring             = 'f1',\n",
    "    random_state        = 42,\n",
    "    n_jobs              = -1,\n",
    "    verbose             = 0\n",
    ")\n",
    "\n",
    "print(f'\\n  ⏳ Menjalankan RandomizedSearchCV (n_iter=20, cv=5)...')\n",
    "print(f'  ⚠️  Proses ini mungkin memakan waktu beberapa menit...')\n",
    "start = time.time()\n",
    "rs_voting.fit(X_train_p, y_train_p)\n",
    "duration = time.time() - start\n",
    "\n",
    "print(f'  ✅ Selesai dalam {duration:.2f} detik')\n",
    "print(f'\\n  📌 Best Parameters:')\n",
    "for k, v in rs_voting.best_params_.items():\n",
    "    print(f'     {k:<25} : {v}')\n",
    "print(f'\\n  Best CV F1-Score : {rs_voting.best_score_:.4f}')\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 87 — Ringkasan Best Parameters
# ═══════════════════════════════════════════════════════════════
comments[87] = [
    "# ============================================================\n",
    "# RINGKASAN BEST PARAMETERS DARI 3 MODEL\n",
    "# ============================================================\n",
    "# Menampilkan parameter optimal yang ditemukan oleh\n",
    "# RandomizedSearchCV untuk masing-masing model.\n",
    "# ============================================================\n",
    "\n",
    "print('=' * 60)\n",
    "print('      RINGKASAN BEST PARAMETERS')\n",
    "print('=' * 60)\n",
    "\n",
    "tuning_results = {\n",
    "    'Logistic Regression' : rs_lr,\n",
    "    'Random Forest'       : rs_rf,\n",
    "    'Voting Classifier'   : rs_voting\n",
    "}\n",
    "\n",
    "for name, rs in tuning_results.items():\n",
    "    print(f'\\n  📌 {name}')\n",
    "    print(f'  {\"─\"*50}')\n",
    "    print(f'  Best CV F1-Score : {rs.best_score_:.4f}')\n",
    "    print(f'  Best Parameters  :')\n",
    "    for k, v in rs.best_params_.items():\n",
    "        print(f'     {k:<25} : {v}')\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 89 — Training Best Estimator
# ═══════════════════════════════════════════════════════════════
comments[89] = [
    "# ============================================================\n",
    "# TRAINING BEST ESTIMATOR — Model dengan Parameter Optimal\n",
    "# ============================================================\n",
    "# Setelah tuning, kita gunakan best_estimator_ yang sudah\n",
    "# memiliki konfigurasi parameter terbaik.\n",
    "#\n",
    "# Model dilatih ULANG menggunakan seluruh data training,\n",
    "# lalu dievaluasi pada data testing untuk hasil final.\n",
    "# ============================================================\n",
    "\n",
    "from sklearn.metrics import (accuracy_score, precision_score,\n",
    "                              recall_score, f1_score,\n",
    "                              confusion_matrix, classification_report)\n",
    "\n",
    "print('=' * 60)\n",
    "print('         TRAINING BEST ESTIMATOR')\n",
    "print('=' * 60)\n",
    "\n",
    "# Ambil model terbaik hasil tuning\n",
    "best_lr     = rs_lr.best_estimator_      # LR dengan parameter optimal\n",
    "best_rf     = rs_rf.best_estimator_      # RF dengan parameter optimal\n",
    "best_voting = rs_voting.best_estimator_  # Voting dengan parameter optimal\n",
    "\n",
    "best_models = {\n",
    "    'Logistic Regression (Tuned)' : best_lr,\n",
    "    'Random Forest (Tuned)'       : best_rf,\n",
    "    'Voting Classifier (Tuned)'   : best_voting\n",
    "}\n",
    "\n",
    "results_tuned = {}  # Simpan hasil evaluasi model tuned\n",
    "\n",
    "for name, model in best_models.items():\n",
    "    print(f'\\n  ⏳ Melatih ulang : {name}...')\n",
    "    start    = time.time()\n",
    "    model.fit(X_train_p, y_train_p)     # Re-training dengan parameter optimal\n",
    "    duration = time.time() - start\n",
    "    y_pred   = model.predict(X_test_p)  # Prediksi pada data test\n",
    "\n",
    "    # Evaluasi 4 metrik\n",
    "    acc  = accuracy_score(y_test_p, y_pred)\n",
    "    prec = precision_score(y_test_p, y_pred)\n",
    "    rec  = recall_score(y_test_p, y_pred)\n",
    "    f1   = f1_score(y_test_p, y_pred)\n",
    "\n",
    "    results_tuned[name] = {\n",
    "        'Accuracy' : acc,\n",
    "        'Precision': prec,\n",
    "        'Recall'   : rec,\n",
    "        'F1-Score' : f1,\n",
    "        'Waktu (s)': round(duration, 2)\n",
    "    }\n",
    "    print(f'  ✅ Selesai {duration:.2f}s | Acc: {acc:.4f} | '\n",
    "          f'Prec: {prec:.4f} | Rec: {rec:.4f} | F1: {f1:.4f}')\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 97 — Simpan Model Terbaik
# ═══════════════════════════════════════════════════════════════
comments[97] = [
    "# ============================================================\n",
    "# SIMPAN MODEL TERBAIK — Export ke File .pkl\n",
    "# ============================================================\n",
    "# Menggunakan joblib untuk serialisasi (menyimpan) 3 artifact:\n",
    "#\n",
    "# 1. best_model.pkl    → Model Random Forest yang sudah dilatih\n",
    "#                        (langsung bisa dipanggil .predict())\n",
    "#\n",
    "# 2. scaler.pkl        → StandardScaler yang sudah di-fit\n",
    "#                        (untuk preprocessing input baru di app)\n",
    "#\n",
    "# 3. feature_names.pkl → List nama fitur (urutan kolom)\n",
    "#                        (agar input form Streamlit sesuai urutan)\n",
    "#\n",
    "# File-file ini akan dipakai oleh app.py (Streamlit) untuk\n",
    "# melakukan prediksi tanpa perlu melatih ulang model.\n",
    "# ============================================================\n",
    "\n",
    "import joblib\n",
    "import os\n",
    "\n",
    "print('=' * 60)\n",
    "print('          SIMPAN MODEL TERBAIK')\n",
    "print('=' * 60)\n",
    "\n",
    "# Buat mapping nama model ke objek model\n",
    "model_map = {}\n",
    "for name, model in models.items():\n",
    "    model_map[f'[Direct] {name}'] = model\n",
    "for name, model in models_prep.items():\n",
    "    model_map[f'[Prep] {name}'] = model\n",
    "for name, model in best_models.items():\n",
    "    model_map[f'[Tuned] {name}'] = model\n",
    "\n",
    "# Ambil model terbaik berdasarkan F1-Score tertinggi\n",
    "best_model_obj = model_map[best_model_name]\n",
    "\n",
    "# Path folder output\n",
    "save_dir = r'c:\\Users\\Lenovo\\OneDrive\\Pictures\\Documents\\KULIAH\\BENGKOD\\UAS-Bengkel-Koding-DataScience\\model'\n",
    "os.makedirs(save_dir, exist_ok=True)\n",
    "\n",
    "# Path file output\n",
    "model_path   = os.path.join(save_dir, 'best_model.pkl')\n",
    "scaler_path  = os.path.join(save_dir, 'scaler.pkl')\n",
    "feature_path = os.path.join(save_dir, 'feature_names.pkl')\n",
    "\n",
    "# Simpan 3 artifact menggunakan joblib\n",
    "joblib.dump(best_model_obj,          model_path)   # Model terbaik\n",
    "joblib.dump(scaler,                  scaler_path)   # Scaler\n",
    "joblib.dump(X_prep.columns.tolist(), feature_path)  # Daftar fitur\n",
    "\n",
    "print(f'\\n  Model terbaik     : {best_model_name}')\n",
    "print(f'     F1-Score          : {best_f1:.4f}')\n",
    "print(f'\\n  File tersimpan di: {save_dir}')\n",
    "print(f'     - best_model.pkl    -> model terbaik untuk prediksi')\n",
    "print(f'     - scaler.pkl        -> StandardScaler untuk preprocessing input')\n",
    "print(f'     - feature_names.pkl -> daftar nama fitur untuk input form')\n",
]

# ═══════════════════════════════════════════════════════════════
# CELL 101 — Verifikasi Artifacts
# ═══════════════════════════════════════════════════════════════
comments[101] = [
    "# ============================================================\n",
    "# STEP 1 — VERIFIKASI MODEL & ARTIFACTS UNTUK DEPLOYMENT\n",
    "# ============================================================\n",
    "# Memastikan semua file yang dibutuhkan untuk deployment\n",
    "# Streamlit sudah tersedia dan bisa di-load dengan benar.\n",
    "#\n",
    "# Test dilakukan dengan:\n",
    "# 1. Cek keberadaan file (os.path.exists)\n",
    "# 2. Load semua artifact (joblib.load)\n",
    "# 3. Prediksi dummy (model.predict dengan input zeros)\n",
    "#    → Jika tidak error, berarti model siap di-deploy!\n",
    "# ============================================================\n",
    "\n",
    "import joblib\n",
    "import os\n",
    "import numpy as np\n",
    "\n",
    "print('=' * 60)\n",
    "print('     STEP 1 - VERIFIKASI MODEL & ARTIFACTS')\n",
    "print('=' * 60)\n",
    "\n",
    "# Path ke folder model\n",
    "save_dir     = r'c:\\Users\\Lenovo\\OneDrive\\Pictures\\Documents\\KULIAH\\BENGKOD\\UAS-Bengkel-Koding-DataScience\\model'\n",
    "model_path   = os.path.join(save_dir, 'best_model.pkl')\n",
    "scaler_path  = os.path.join(save_dir, 'scaler.pkl')\n",
    "feature_path = os.path.join(save_dir, 'feature_names.pkl')\n",
    "\n",
    "# Daftar file yang perlu dicek\n",
    "files_to_check = {\n",
    "    'best_model.pkl'   : model_path,\n",
    "    'scaler.pkl'       : scaler_path,\n",
    "    'feature_names.pkl': feature_path\n",
    "}\n",
    "\n",
    "# Cek keberadaan setiap file\n",
    "print(f'\\n  Cek ketersediaan file artifacts:')\n",
    "all_ok = True\n",
    "for fname, fpath in files_to_check.items():\n",
    "    exist  = os.path.exists(fpath)\n",
    "    size   = f'{os.path.getsize(fpath)/1024:.1f} KB' if exist else '-'\n",
    "    status = '[OK]' if exist else '[MISSING]'\n",
    "    print(f'  {status} {fname:<25} {size}')\n",
    "    if not exist:\n",
    "        all_ok = False\n",
    "\n",
    "if all_ok:\n",
    "    # Load semua artifact\n",
    "    loaded_model    = joblib.load(model_path)\n",
    "    loaded_scaler   = joblib.load(scaler_path)\n",
    "    loaded_features = joblib.load(feature_path)\n",
    "\n",
    "    print(f'\\n  Detail Artifacts:')\n",
    "    print(f'     Model type     : {type(loaded_model).__name__}')\n",
    "    print(f'     Jumlah fitur   : {len(loaded_features)}')\n",
    "    print(f'     Scaler type    : {type(loaded_scaler).__name__}')\n",
    "\n",
    "    # Test prediksi dummy → pastikan pipeline berjalan end-to-end\n",
    "    dummy        = np.zeros((1, len(loaded_features)))    # Input dummy (semua 0)\n",
    "    dummy_scaled = loaded_scaler.transform(dummy)          # Scale input\n",
    "    pred         = loaded_model.predict(dummy_scaled)      # Prediksi\n",
    "    print(f'\\n  Test prediksi dummy berhasil -> output: {pred[0]}')\n",
    "    print(f'  Semua artifacts siap untuk deployment!')\n",
    "else:\n",
    "    print(f'\\n  Ada file yang belum tersedia. Jalankan ulang cell simpan model!')\n",
]

# ───────────────────────────────────────────────────────────────
#  APPLY COMMENTS TO NOTEBOOK
# ───────────────────────────────────────────────────────────────

nb_new = copy.deepcopy(nb)

for cell_idx, new_source in comments.items():
    nb_new['cells'][cell_idx]['source'] = new_source

# Save
with open('notebook/UAS_BENGKOD.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb_new, f, ensure_ascii=False, indent=1)

print(f"✅ Berhasil menambahkan komentar ke {len(comments)} code cells!")
print(f"   Backup tersimpan di: notebook/UAS_BENGKOD_BACKUP.ipynb")
print(f"   Notebook updated  : notebook/UAS_BENGKOD.ipynb")
